### PR TITLE
implemented instrumentation for Groovy class files.

### PR DESCRIPTION
**Pull request by jcabraham**
Just added a test model class called Company.groovy, a groovy instrumentation test, and basically duplicated code in the plugin to do the implementation on a groovy classes directory. Rev'ed the version to 1.3.

### CODE REVIEW

**Comment by jcabraham** [comment]
WARNING: This builds and the tests run, but I'm getting a class not found exception when using the plugin in my project. 

build.gradle:
```

buildscript {
    repositories {
        flatDir name: 'lib', dirs: "./lib"
    }
    dependencies {
        classpath 'de.schablinski:activejdbc-gradle-plugin:1.3'
    }
}

apply plugin: 'groovy'	
apply plugin: 'java'	
apply plugin: 'war'
apply plugin: 'de.schablinski.activejdbc-gradle-plugin'

activejdbc.toolVersion = 2.3

repositories {
    mavenCentral()
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://build.shibboleth.net/nexus/content/repositories/releases/' }
}

dependencies {
    compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.8'
    compile group: 'com.sparkjava', name: 'spark-core', version: '2.9.1'
    compile group: 'com.sparkjava', name: 'spark-template-thymeleaf', version: '2.7.1'
    compile group: 'org.thymeleaf', name: 'thymeleaf', version: '3.0.11.RELEASE'
    compile group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.12.1'

    compile group: 'org.pac4j', name: 'pac4j-saml', version: '3.7.0'
    compile group: 'org.pac4j', name: 'spark-pac4j', version: '3.0.0'

    compile group: 'org.javalite', name: 'activejdbc', version: '3.0-SNAPSHOT'
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.6.jre7'
    implementation 'org.javalite:activejdbc-gradle-plugin:2.2'
}
```
```
> ./gradlew --stacktrace compileGroovy
...
Caused by: java.lang.NoClassDefFoundError: org/javalite/instrumentation/Main
        at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation$_runInstrumentation_closure1.doCall(ActiveJDBCInstrumentation.groovy:83)
```

**Comment by cschabl** [comment]
Your dependencies don't make sense. You use ActiveJdbc 2.3 for the gradle plugin. Then you have ActiveJdbc 3.0 Snapshot and the old ActiveJdbc gradle plugin 2.2 on your compile classpath. I haven't tested the new gradle plugin with ActiveJdbc 3.0 Snapshot.


-------- Ursprüngliche Nachricht --------
Von: Jim Abraham <notifications@github.com> 
Datum: 28.08.2019  22:00  (GMT+01:00) 
An: cschabl/activejdbc-gradle-plugin <activejdbc-gradle-plugin@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: Re: [cschabl/activejdbc-gradle-plugin] implemented instrumentation
  for Groovy class files. (#6) 

WARNING: This builds and the tests run, but I'm getting a class not found exception when using the plugin in my project.

build.gradle:


buildscript {
    repositories {
        flatDir name: 'lib', dirs: "./lib"
    }
    dependencies {
        classpath 'de.schablinski:activejdbc-gradle-plugin:1.3'
    }
}

apply plugin: 'groovy'	
apply plugin: 'java'	
apply plugin: 'war'
apply plugin: 'de.schablinski.activejdbc-gradle-plugin'

activejdbc.toolVersion = 2.3

repositories {
    mavenCentral()
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://build.shibboleth.net/nexus/content/repositories/releases/' }
}

dependencies {
    compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.8'
    compile group: 'com.sparkjava', name: 'spark-core', version: '2.9.1'
    compile group: 'com.sparkjava', name: 'spark-template-thymeleaf', version: '2.7.1'
    compile group: 'org.thymeleaf', name: 'thymeleaf', version: '3.0.11.RELEASE'
    compile group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.12.1'

    compile group: 'org.pac4j', name: 'pac4j-saml', version: '3.7.0'
    compile group: 'org.pac4j', name: 'spark-pac4j', version: '3.0.0'

    compile group: 'org.javalite', name: 'activejdbc', version: '3.0-SNAPSHOT'
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.6.jre7'
    implementation 'org.javalite:activejdbc-gradle-plugin:2.2'
}
> ./gradlew --stacktrace compileGroovy
...
Caused by: java.lang.NoClassDefFoundError: org/javalite/instrumentation/Main
        at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation$_runInstrumentation_closure1.doCall(ActiveJDBCInstrumentation.groovy:83)

**Comment by cschabl** [comment]
I won't be able to merge your PR the next 2 weeks since I'm on vacation.

**Comment by jcabraham** [comment]
Those were what I was using with your published plugin, the only issue with it was it was unaware of, basically, classes/groovy. In any case, I tried again with activejdbc 2.3 and tool version 2.2, across the board, viz:

```
buildscript {
    repositories {
        flatDir name: 'lib', dirs: "./lib"
    }
    dependencies {
        classpath 'de.schablinski:activejdbc-gradle-plugin:1.3'
    }
}

plugins {
    id 'org.gretty' version '2.3.1'
}

apply plugin: 'idea'
apply plugin: 'eclipse'
apply plugin: 'groovy'	
apply plugin: 'java'	
apply plugin: 'war'
apply plugin: 'de.schablinski.activejdbc-gradle-plugin'

def activeJdbcVersion = 2.3
activejdbc.toolVersion = 2.3

repositories {
    mavenCentral()
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://build.shibboleth.net/nexus/content/repositories/releases/' }
}

dependencies {
    implementation group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.8'
    implementation group: 'com.sparkjava', name: 'spark-core', version: '2.9.1'
    implementation group: 'com.sparkjava', name: 'spark-template-thymeleaf', version: '2.7.1'
    implementation group: 'org.thymeleaf', name: 'thymeleaf', version: '3.0.11.RELEASE'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.12.1'

    implementation group: 'org.pac4j', name: 'pac4j-saml', version: '3.7.0'
    implementation group: 'org.pac4j', name: 'spark-pac4j', version: '3.0.0'

    implementation group: 'org.javalite', name: 'activejdbc', version: "$activeJdbcVersion"
    implementation group: 'org.javalite', name: 'activejdbc-instrumentation', version: "$activeJdbcVersion"
    implementation group: 'org.javalite', name: 'activejdbc-gradle-plugin', version: '2.2'
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.6.jre7'
}
```
Same exception. It's thrown here:

`    private void runInstrumentation(FileCollection instrumentationClasspath, String outputDirpath) {
        project.javaexec { JavaExecSpec jes ->
            logger.info "Running ActiveJDBC instrumentation instance with environment: ${jes.environment}"

            jes.classpath = instrumentationClasspath
            jes.main = Main.canonicalName //<----
            jes.systemProperties = ['outputDirectory': outputDirpath]
        }
    }`

So, the plugin, at runtime, can't find org.javalite.instrumentation.Main. If you replace Main.canonicalName with the string 'org.javalite.instrumentation.Main', everything works. So this is obviously a classloader issue which I'm apparently not bright enough or diligent enough to, ahem, resolve. Anyway, I have a version which works, but probably not one which can be released without further effort. Please feel free to just reject the PR. Regards,




> Your dependencies don't make sense. You use ActiveJdbc 2.3 for the gradle plugin. Then you have ActiveJdbc 3.0 Snapshot and the old ActiveJdbc gradle plugin 2.2 on your compile classpath. I haven't tested the new gradle plugin with ActiveJdbc 3.0 Snapshot.
> -------- Ursprüngliche Nachricht -------- Von: Jim Abraham <notifications@github.com> Datum: 28.08.2019 22:00 (GMT+01:00) An: cschabl/activejdbc-gradle-plugin <activejdbc-gradle-plugin@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [cschabl/activejdbc-gradle-plugin] implemented instrumentation for Groovy class files. (#6) WARNING: This builds and the tests run, but I'm getting a class not found exception when using the plugin in my project. build.gradle: buildscript { repositories { flatDir name: 'lib', dirs: "./lib" } dependencies { classpath 'de.schablinski:activejdbc-gradle-plugin:1.3' } } apply plugin: 'groovy' apply plugin: 'java' apply plugin: 'war' apply plugin: 'de.schablinski.activejdbc-gradle-plugin' activejdbc.toolVersion = 2.3 repositories { mavenCentral() jcenter() maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' } maven { url 'https://build.shibboleth.net/nexus/content/repositories/releases/' } } dependencies { compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.8' compile group: 'com.sparkjava', name: 'spark-core', version: '2.9.1' compile group: 'com.sparkjava', name: 'spark-template-thymeleaf', version: '2.7.1' compile group: 'org.thymeleaf', name: 'thymeleaf', version: '3.0.11.RELEASE' compile group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.12.1' compile group: 'org.pac4j', name: 'pac4j-saml', version: '3.7.0' compile group: 'org.pac4j', name: 'spark-pac4j', version: '3.0.0' compile group: 'org.javalite', name: 'activejdbc', version: '3.0-SNAPSHOT' implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.6.jre7' implementation 'org.javalite:activejdbc-gradle-plugin:2.2' }
> ./gradlew --stacktrace compileGroovy
> ... Caused by: java.lang.NoClassDefFoundError: org/javalite/instrumentation/Main at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation$_runInstrumentation_closure1.doCall(ActiveJDBCInstrumentation.groovy:83) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cschabl** [comment]
@jcabraham, I published the plugin as version 1.3-beta.1 to the Gradle plugin portal. 
I also created an [example project](https://github.com/cschabl/active-jdbc-gradle-groovy-example) that uses this latest version of the plugin and an ActiveJDBC model class written in Groovy. Currently, the project only supports the ActiveJDBC instrumentation. I plan to add tests demonstrating the usage of the model classes soon.

Could you test the activejdbc-gradle-plugin:1.3-beta.1 in your project as demonstrated in the example project?

**Comment by jcabraham** [comment]
Works, thanks so much for you patience with a gradle newbie.

Jim

**Comment by cschabl** [comment]
Thanks for the integration test. I published the plugin as version 1.3 to the Gradle plugin portal

**Pull request merged**
